Repository Accenture/sfmc-devtools-copado, pull requests merged in 2022-10, with the labels that each got.

#108 wrong date bug fix
  copado-function/app/Commit.js
  copado-function/app/Deploy.js
  copado-function/app/Retrieve.js
  copado-function/app/Upgrade.js
Labels: bug

#121 #120 Result Data and Error Message not getting updated on job execution + result record
  copado-function/app/Commit.js
  copado-function/app/Deploy.js
  copado-function/app/Retrieve.js
  copado-function/app/Upgrade.js
Labels: bug

#126 #125: set tabWidth and printWidth
  .prettierrc
Labels: chore

#90 #03 platform event even after the function result completed
  .vscode/settings.json
  force-app/main/default/lwc/marketingCloudCopadoDataTable/marketingCloudCopadoDataTable.js
Labels: bug

#129 127 feature user logresult logerror to properly save status
  .husky/commit-msg
  .husky/post-checkout
  copado-function/app/Commit.js
  copado-function/app/Deploy.js
  copado-function/app/Retrieve.js
  copado-function/app/Upgrade.js
Labels: enhancement

#136 #135: apply filters on execSync result to get proper array from git diff
  copado-function/app/Commit.js
Labels: bug

#139 #138: apply auto-formatting via Eslint/Prettier
  .markdownlint.md
  README.md
  force-app/main/default/aura/.eslintrc.json
  force-app/main/default/classes/ChildEnvironmentVariableController.cls
  force-app/main/default/classes/ChildEnvironmentVariableController.cls-meta.xml
  force-app/main/default/classes/ChildEnvironmentVariables.cls
  force-app/main/default/classes/ChildEnvironmentVariables.cls-meta.xml
  force-app/main/default/classes/ChildEnvironmentVariablesTest.cls
  force-app/main/default/classes/ChildEnvironmentVariablesTest.cls-meta.xml
  force-app/main/default/classes/MCDO_RetrieveCompletion.cls
  force-app/main/default/classes/MCDO_RetrieveCompletion.cls-meta.xml
  force-app/main/default/classes/RunCopadoFunctionFromLWC.cls
  force-app/main/default/classes/RunCopadoFunctionFromLWC.cls-meta.xml
  force-app/main/default/classes/RunCopadoFunctionFromLWCTest.cls
  force-app/main/default/classes/RunCopadoFunctionFromLWCTest.cls-meta.xml
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/classes/TestDataFactory.cls-meta.xml
  force-app/main/default/lwc/.eslintrc.json
  force-app/main/default/lwc/childEnvironmentVariables/childEnvironmentVariables.css
  force-app/main/default/lwc/childEnvironmentVariables/childEnvironmentVariables.html
  force-app/main/default/lwc/childEnvironmentVariables/childEnvironmentVariables.js
  force-app/main/default/lwc/childEnvironmentVariables/childEnvironmentVariables.js-meta.xml
  force-app/main/default/lwc/marketingCloudCopadoDataTable/marketingCloudCopadoDataTable.css
  force-app/main/default/lwc/marketingCloudCopadoDataTable/marketingCloudCopadoDataTable.html
  force-app/main/default/lwc/marketingCloudCopadoDataTable/marketingCloudCopadoDataTable.js-meta.xml
  force-app/main/default/objects/copado__Environment__c/fields/Parent_Environment__c.field-meta.xml
  force-app/main/default/permissionsets/Copado_Marketing_Cloud_Extension.permissionset-meta.xml
  jest.config.js
  jsconfig.json
  package-lock.json
  package.json
  sfdx-project.json
Labels: chore, PRIORITY, sfdc

#157 155 task commitjs should use logerror not logresult if it did not find anything to commit
  copado-function/app/Commit.js
Labels: chore

#144 35 feature rewrite deploy function to allow deploy without git diff
  copado-function/app/Commit.js
  copado-function/app/Deploy.config
  copado-function/app/Deploy.js
  copado-function/app/Retrieve.js
Labels: enhancement

#159 154 feature update retrievetarget bu on master branch as part of deploy
  copado-function/app/Commit.js
  copado-function/app/Deploy.config
  copado-function/app/Deploy.js
  copado-function/app/Retrieve.js
Labels: enhancement

#160 #34 error message hyperlink with jobid
  force-app/main/default/lwc/marketingCloudCopadoDataTable/marketingCloudCopadoDataTable.js
Labels: bug

#156 Feature/148 browser console
  force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.js
Labels: bug

#181 #149 bug selecting items and doing multiple searches breaks on commit page
  force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.html
  force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.js
Labels: bug, PRIORITY

#188 187 bug if recreate branch is selected and the delete fails we should handle it gracefully
  copado-function/app/Commit.js
  copado-function/app/Deploy.js
  copado-function/app/Retrieve.js
Labels: bug

#193 #191: only print progress messages for my own jobExecution
  force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.js
Labels: bug

#194 177 feature improve speed of execution for mcdevretrieve with type key combos
  copado-function/app/Commit.js
  copado-function/app/Deploy.js
Labels: enhancement, node.js

#195 171 bug race condition during mass backpromote
  copado-function/app/Deploy.js
Labels: bug

#199 #196: reverting prior filter
  force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.js
Labels: bug, sfdc

#207 #205: fix commit result message on windows
  copado-function/app/Commit.js
Labels: bug

#214 #213 bug automation lastmodifieddate is empty if automation was never changed after creation
  copado-function/app/Commit.config
  copado-function/app/Promote.config
  copado-function/app/Retrieve.js
Labels: bug

#220 #218: ensuring mcdev logs are uploaded in case of error
  copado-function/app/Commit.js
Labels: bug

#224 #223: retrieve assets with subtypes
  copado-function/app/Retrieve.js
Labels: enhancement

#253 #231 bug infinite time spinner if no records to show
  copado-function/app/Commit.js
  copado-function/app/Deploy.js
  copado-function/app/Retrieve.js
  force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.js
Labels: bug

#258 257 feature take u param of copado deploy changesjson to enhance commit msg for target
  copado-function/app/Commit.js
  copado-function/app/Deploy.config
  copado-function/app/Deploy.js
  copado-function/app/environments/Commit.env-sample
  copado-function/app/environments/Deploy.env-sample
Labels: node.js

#259 242 bug verification of deploy assets fails with no files found
  copado-function/app/Commit.config
  copado-function/app/Commit.js
  copado-function/app/Deploy.config
  copado-function/app/Deploy.js
  copado-function/app/PIPELINE.config
  copado-function/app/Retrieve.config
  copado-function/app/Retrieve.js
Labels: bug

#261 #249: clean up logs
  copado-function/app/Commit.js
  copado-function/app/Deploy.js
  copado-function/app/Retrieve.js
Labels: chore

#263 #262: allow 1:n deployemts on single target BU
  copado-function/app/Deploy.config
  copado-function/app/Deploy.js
Labels: PRIORITY, Copado-GUI, node.js

#269 264 feature auto get child envs of child if there are any
  copado-function/app/Commit.js
  copado-function/app/Deploy.js
  copado-function/app/Retrieve.js
  copado-function/app/mcdev-retrieveTypes.config
  force-app/main/default/classes/mcdo_ChildEnvironmentVariables.cls
  force-app/main/default/flexipages/Environment_Record_Page2.flexipage-meta.xml
  force-app/main/default/layouts/copado__Environment__c-copado__Environment Layout.layout-meta.xml
  force-app/main/default/objects/copado__Environment__c/fields/mcdo_Is_Enterprise_BU__c.field-meta.xml
  force-app/main/default/permissionsets/Copado_Marketing_Cloud.permissionset-meta.xml
Labels: enhancement
